# Sample values file for using external PostgreSQL and Redis

## Global configuration
global:
  env: production

## Outline application configuration
outline:
  replicaCount: 1

  image:
    repository: outlinewiki/outline
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: wiki.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: outline-tls
        hosts:
          - wiki.example.com

  env:
    URL: "https://wiki.example.com"
    PORT: 3000
    FILE_STORAGE: local

    # Authentication (example with Google - you need at least one auth provider)
    GOOGLE_CLIENT_ID: "your-google-client-id"
    GOOGLE_CLIENT_SECRET: "your-google-client-secret"

  envSecrets:
    # Generate using: openssl rand -hex 32
    SECRET_KEY: "replace-with-a-random-key"
    UTILS_SECRET: "replace-with-a-random-key"

  persistence:
    enabled: true
    size: 10Gi

## PostgreSQL configuration - using external database
postgresql:
  enabled: false
  external:
    host: "your-postgres-host.example.com"
    port: 5432
    database: "outline"
    user: "outline"
    password: "your-secure-password"
    # Alternatively, use an existing secret
    # existingSecret: "postgres-credentials"
    # existingSecretKey: "password"

## Redis configuration - using external Redis
redis:
  enabled: false
  external:
    host: "your-redis-host.example.com"
    port: 6379
    password: "your-redis-password"
    # Alternatively, use an existing secret
    # existingSecret: "redis-credentials"
    # existingSecretKey: "redis-password"
