{{- if .Values.outline.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "outline.fullname" . }}-data
  labels:
    {{- include "outline.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.outline.persistence.accessMode }}
  {{- if .Values.outline.persistence.storageClass }}
  storageClassName: {{ .Values.outline.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.outline.persistence.size | quote }}
{{- end }}
