name: Release Helm Charts


on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Chart version bump level"
        required: true
        type: choice
        default: minor
        options:
          - minor
          - patch
      force_version:
        description: "Force a chart version (ignore Chart bump level)"
      mark_latest:
        description: "Mark this release as the latest"
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Bump Outline chart version
        id: chart-version
        working-directory: charts/outline
        run: |
          CHART_VERSION="${{ github.event.inputs.force_version }}"

          if [ -z "${CHART_VERSION}" ]; then
            current="$(grep -m 1 '^version:' Chart.yaml | awk '{print $2}')"

            RE='([0-9]+)\.([0-9]+)\.([0-9]+)'

            MAJOR=`echo $current | sed -E "s#$RE#\1#"`
            MINOR=`echo $current | sed -E "s#$RE#\2#"`
            PATCH=`echo $current | sed -E "s#$RE#\3#"`

            if [ "${{ github.event.inputs.bump }}" == "minor" ]; then
              MINOR=$((MINOR+1))
              PATCH=0
            else
              PATCH=$((PATCH+1))
            fi
            CHART_VERSION="$MAJOR.$MINOR.$PATCH"
          fi

          echo "chart_version=$CHART_VERSION" >> "$GITHUB_OUTPUT"

      - name: Configure Git
        run: |
          git config user.name "itsneel"
          git config user.email "itsneel@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Add external Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          mark_as_latest: "${{ github.event.inputs.mark_latest }}"
        env:
          CR_TOKEN: "${{ secrets.PAT }}"
